No data values
conveyal/gridualizer pull request #7
Opened 2017-01-02 20:53 UTC by mattwigway

Allow specifying no data values in choropleth layers, depends on #6.

2017-01-03 16:50 UTC, trevorgerhardt requested changes

2017-01-03 16:50 UTC, trevorgerhardt commented on package.json
> +    "prepublish": "mastarm prepublish lib:build/lib",
Ah, use `mastarm prepublish lib --outdir build`

2017-01-03 16:50 UTC, trevorgerhardt commented on package.json
> +    "prepublish": "mastarm prepublish lib:build/lib",
Undocumented feature in mastarm...need to update the docs 😬

2017-01-03 17:19 UTC, mattwigway commented
Done. Ready to go otherwise @trevorgerhardt?

2017-01-04 03:25 UTC, trevorgerhardt approved these changes

2017-01-04 14:00 UTC, merged